# version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: db-prueba
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: prueba-tecnica
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - ./mongo-data:/data/db


  backend:
    container_name: backend
    depends_on:
      - mongo
    build:
      context: ./samla
      dockerfile: Dockerfile
    environment:
      - PORT=${BACKEND_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_URL=http://front:3000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - JWT_SECRET=${JWT_SECRET}

    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    

  front:
    depends_on:
      - backend
    container_name: front
    build:
      context: ./front-samla
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    environment:
      - FRONT_PORT=${FRONT_PORT}
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - '${FRONT_PORT}:80'

volumes:
  mongo-data:
