name: Sync development branches
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          message: '[auto-merge] Sync main -> develop (${{ github.sha }})'
          target_branch: main
          github_token: ${{ secrets.ACCESS_TOKEN }}